[project]
name = "Segment Anything 2 Realtime (Fork)"
version = "0.1.1"
description = "A brief description of your project"
dependencies = [
    "sam2_realtime @ file://./sam2_realtime"
]

[build-system]
requires = [
    "setuptools>=61.0",  
    "torch>=2.3.1",
    ]
build-backend = "setuptools.build_meta"
